version: "3.9"
services:
  database:
    container_name: database
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: bank
    expose:
      - 3306
    ports:
      - "3306:3306"
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-uroot', '-proot']
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 30s
  
  server:
    container_name: pyro-bank-server
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    expose:
      - 9090
