version: "3"
services:
  server:
    container_name: node-server
    depends_on:
      - mongo
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
    - '27017:27017'