version: "3.8"
services:
  mariadb-server:
    container_name: mariadb-server
    image: mariadb
    user: root
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      
  server:
    depends_on:
      - mariadb-server
    build:
      context: ./Server_ATM
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
