version: "3.8"
services:
  database:
    container_name: database
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: bank
    ports:
      - "3306:3306"
    expose:
      - 3306

  server:
    container_name: server
    build:
      context: ./Server_ATM
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    expose:
      - 8080