version: "3.9"
services:
  database:
    container_name: database
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-u', 'root', '-proot' ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  
  server:
    container_name: server
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    build:
      context: ./Server_ATM
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080